### ISSUE TITLE
Trying to create a variable

### ISSUE THREAD

**Issue by Tonts95** [bitfocus/companion-module-riedel-rrcs#7]
Hi,

I'm looking for a way to increase (by 1dB steps) or decrease (by -1dB steps) the output gain of a given port using the encoders of a StreamDeck+. I think that I need to write a variable in the "IO Gain (dB)" section of the "Port - Set IO gain" function to do that, and that's what is loosing me.

So far, I can set the gain to a given value by turning the encoder to the right, and to another value by turning the gain to the left by using the "Rotary actions" of a Companion button, and using the port adress, and not the port list.

And second thing, the must would be that a press on the encoder of the StreamDeck+ would mute the output (set the gain to -64dB), and a second press would restore the output gain to the last known value, just before the mute.

Thank you in advance.

**Comment by phillipivan** [comment]
Hi,

You can use a custom variable in the set output gain action. You will need to stack an internal action to increase or decrease the custom variable value before the Set Output gain action, to achieve this rotary function. Sorry it's not easier but for now RRCS doesn't generate notifications for output port gain changes, so tracking the value in the Artist would require tracking which ones we care about and frequent polling. 

With regards to the second part, I think the output gain range is only +/- 18 dB. ~~So you will not be able to use it as way to mute.

Perhaps you could have a Set logic source action, and do it in the Artist Matrix with some logic.~~

Edit to add: The above details regarding muting was from memory and is incorrect.

**Comment by phillipivan** [comment]
For the mute: Try setting the gain to -65 to see if that mutes. I have a less than comparison when I probably need a less than or equal to. If that works I will issue a new patch.

**Comment by Tonts95** [comment]
Hi,

I just finished writing the variables to increase and decrease the output gain, and it works great. Thanks for the tip.

And indeed, -65 mute the output.

Now it will be time to play with the other functions.

**Comment by phillipivan** [comment]
Excellent. I will issue a patch so it works at -64 as expected (I just needed to use a <= rather than a <).

**Comment by phillipivan** [comment]
Muting fixed in 1.0.5
